language: python
python: 2.7

install:
  - if [ "$HG_VERSION" != "dev" ];
    then pip install Mercurial${HG_VERSION+==$HG_VERSION};
    else pip install http://selenic.com/repo/hg/archive/tip.tar.gz;
    fi

before_script:
  - hg --version || true

script:
  - make test

matrix:
  include:
    - env: HG_VERSION=dev
    - env: HG_VERSION=5.0
    - env: HG_VERSION=4.9
    - env: HG_VERSION=4.8
    - env: HG_VERSION=4.7
    - env: HG_VERSION=4.6
    - env: HG_VERSION=4.5
